; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "WMS"
#define MyAppVersion "2.1.8"
#define MyAppPublisher "Globagility, Inc."
#define MyAppURL "globagilityinc.com"
#define MyAppExeName "Warehouse Management System.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DAD406CF-6F8C-4E55-9B6F-6001EBD5C705}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\GLOBAGILITY\WMS
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
; PrivilegesRequired=lowest
PrivilegesRequired=lowest
OutputBaseFilename={#MyAppName}-setup-v{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: ".\bin\Debug\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\bin\Debug\*.dll"; DestDir: "{app}"; Flags: ignoreversion

Source: ".\bin\Debug\Import Templates\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: ".\Import Templates\*.xlsx"; DestDir: "{app}\Import Templates"; Flags: ignoreversion
Source: ".\Report Files\DeliveryReceipt\*.json"; DestDir: "{app}\Report Files\DeliveryReceipt"; Flags: ignoreversion
Source: ".\Report Files\DeliveryReceipt\*.xlsx"; DestDir: "{app}\Report Files\DeliveryReceipt"; Flags: ignoreversion
Source: ".\Report Files\GatePass\*.xlsx"; DestDir: "{app}\Report Files\GatePass"; Flags: ignoreversion

Source: ".\bin\Debug\log4.config"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\bin\Debug\Warehouse Management System.exe.config"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

