/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP PROCEDURE IF EXISTS `U_lineups`;
DELIMITER //
CREATE PROCEDURE `U_lineups`(
	IN `U_RowID` INT(11),
	IN `U_LastUpd` DATETIME,
	IN `U_LastUpdBy` INT(11),
	IN `U_ContactID` INT(11),
	IN `U_DeliveryTruckShiftID` INT(11),
	IN `U_LineUpDate` DATE,
	IN `U_DeliveryNo` VARCHAR(50),
	IN `U_Comments` VARCHAR(100),
	IN `U_AgentId` INT,
	IN `U_Helper1Id` INT,
	IN `U_Helper2Id` INT
)
BEGIN
UPDATE lineups SET
	LastUpd = U_LastUpd,
	LastUpdBy = U_LastUpdBy,
	ContactID = U_ContactID,
	DeliveryTruckShiftID = U_DeliveryTruckShiftID,
	LineUpDate = U_LineUpDate,
	DeliveryNo = U_DeliveryNo,
	Comments = U_Comments,
	`AgentId` = U_AgentId,
	`Helper1Id` = U_Helper1Id,
	`Helper2Id` = U_Helper2Id
WHERE RowID = U_RowID;
END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
