/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP PROCEDURE IF EXISTS `U_packinglistcartons`;
DELIMITER //
CREATE PROCEDURE `U_packinglistcartons`(IN `U_RowID` INT(11), IN `U_LastUpd` DATETIME, IN `U_LastUpdBy` INT(11), IN `U_ContactID` INT(11), IN `U_CartonSizeID` INT(11), IN `U_CartonNo` VARCHAR(50), IN `U_PackedDate` DATE, IN `U_WeightUOM` VARCHAR(50), IN `U_Weight` DECIMAL(10,2), IN `U_Amount` DECIMAL(10,4))
BEGIN
UPDATE packinglistcartons SET
	LastUpd = U_LastUpd,
	LastUpdBy = U_LastUpdBy,
	ContactID = U_ContactID,
	CartonSizeID = U_CartonSizeID,	
	CartonNo = U_CartonNo,
	PackedDate = U_PackedDate,
	WeightUOM = U_WeightUOM, 
	`Weight` = U_Weight,
	`Amount` = U_Amount
WHERE RowID = U_RowID;
END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
