/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP PROCEDURE IF EXISTS `U_address`;
DELIMITER //
CREATE PROCEDURE `U_address`(IN `U_RowID` INT(11), IN `U_LastUpd` DATETIME, IN `U_LastUpdBy` INT(11), IN `U_StreetAddress1` VARCHAR(100), IN `U_StreetAddress2` VARCHAR(100), IN `U_Barangay` VARCHAR(50), IN `U_CityTown` VARCHAR(50), IN `U_Province` VARCHAR(50), IN `U_State` VARCHAR(50), IN `U_ZipCode` VARCHAR(50), IN `U_Country` VARCHAR(50))
BEGIN
UPDATE address SET
	LastUpd = U_LastUpd,
	LastUpdBy = U_LastUpdBy,
	StreetAddress1 = U_StreetAddress1,
	StreetAddress2 = U_StreetAddress2,
	Barangay = U_Barangay,
	CityTown = U_CityTown,
	Province = U_Province,
	State = U_State,
	ZipCode = U_ZipCode,
	Country = U_Country
WHERE RowID = U_RowID;
END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
