/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP PROCEDURE IF EXISTS `U_users`;
DELIMITER //
CREATE PROCEDURE `U_users`(IN `U_RowID` INT(11), IN `U_LastUpd` DATETIME, IN `U_LastUpdBy` INT(11), IN `U_UserID` VARCHAR(50), IN `U_Password` VARCHAR(50), IN `U_PositionID` INT(11), IN `U_FirstName` VARCHAR(50), IN `U_MiddleName` VARCHAR(50), IN `U_LastName` VARCHAR(50), IN `U_EmailAddress` VARCHAR(50), IN `U_Status` VARCHAR(50), IN `U_Comments` VARCHAR(500))
BEGIN
UPDATE users SET 
	LastUpd = U_LastUpd,
	LastUpdBy = U_LastUpdBy,
	UserID = U_UserID,
	`Password` = U_Password,
	PositionID = U_PositionID,
	FirstName = U_FirstName,
	MiddleName = U_MiddleName,
	LastName = U_LastName,
	EmailAddress = U_EmailAddress,
	`Status` = U_Status,
	Comments = U_Comments
WHERE RowID = U_RowID;
END//
DELIMITER ;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
