<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Services\OrderService\**" />
    <EmbeddedResource Remove="Data\Services\OrderService\**" />
    <None Remove="Data\Services\OrderService\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\System.Core\WarehouseManagementSystem.Core.csproj" />
    <ProjectReference Include="..\System.Utilities\WarehouseManagementSystem.Utilities.csproj" />
  </ItemGroup>

</Project>
